[tools]
node = ["22.22.0", "24.13.1"]
java = "latest"
python = "3.13"
go = "latest"
action-validator = "latest"
"npm:@antfu/ni" = "30.1.0"
"npm:@kitlangton/ghui" = "latest"
tuist = "latest"
"github:can1357/oh-my-pi" = "latest"

"npm:typescript-language-server" = "latest"
"npm:pyright" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"aqua:astral-sh/ruff" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"pipx:debugpy" = "latest"
"dotnet:csharp-ls" = "latest"
"github:Samsung/netcoredbg" = "3.2.0-1092"
