#!▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄

#? █▀▀ █▀█ █▄░█ █▀▀ █ █▀▀ █░█ █▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
#? █▄▄ █▄█ █░▀█ █▀░ █ █▄█ █▄█ █▀▄ █▀█ ░█░ █ █▄█ █░▀█

#!▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄

# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Change your personal monitor setup in here to keep the main config portable
source = ~/.config/hypr/monitors.conf

#!▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄

#? █▀▄ █▀▀ █▀▀ ▄▀█ █░█ █░░ ▀█▀   ▄▀█ █▀█ █▀█ █░░ █ █▀▀ ▄▀█ ▀█▀ █ █▀█ █▄░█ █▀
#? █▄▀ ██▄ █▀░ █▀█ █▄█ █▄▄ ░█░   █▀█ █▀▀ █▀▀ █▄▄ █ █▄▄ █▀█ ░█░ █ █▄█ █░▀█ ▄█

#!▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄

# Default applications
$browser = omarchy-launch-browser
$discord = uwsm app -- discord
$fileManager = uwsm app --  nautilus --new-window
$messenger = uwsm app --  signal-desktop
$music = uwsm app --  spotify
$passwordManager = uwsm app --  1password
$screenshot = uwsm app --  hyprshot
$terminal = uwsm app --  ghostty
$webapp = uwsm app --  chromium --app

#!▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄

#? █░█ █▀ █▀▀ █▀█   █▀▄ █▀▀ █▀▀ ▄▀█ █░█ █░░ ▀█▀ █▀
#? █▄█ ▄█ ██▄ █▀▄   █▄▀ ██▄ █▀░ █▀█ █▄█ █▄▄ ░█░ ▄█

#!▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄

source = ~/.config/hypr/unbinds.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/userprefs.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/autostart.conf

# Machine-specific config (not tracked in git, optional - glob pattern won't error if missing)
source = ~/.config/hypr/hyprland.local*.conf
