return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "biome",
      "black",
      "pyright",
      "autopep8",
      "flake8",
      "isort",
      "debugpy",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "eslint-lsp",
      "graphql-language-service-cli",
      "json-lsp",
      "lua-language-server",
      "luacheck",
      "prettier",
      "rust-analyzer",
      "ruff",
      "shellcheck",
      "shfmt",
      "stylua",
      "tailwindcss-language-server",
      "typescript-language-server",
      "yaml-language-server",
      "yamlfmt",
      "yamllint",
      "svelte-language-server",
    },
  },
}
